[LM-12845] Migration to Target SDK 34
sidcr7-likeminds/LikeMinds-Android-Feed-CH pull request #25
Opened 2024-10-23 10:54 UTC by ishaan1607

## Description

**Features**
- Migration to Target SDK 34

**Bugs**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Hotfix (fix for breaking changes)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Other, please describe:

### Author Checklist

- [x] Assignee added
- [x] Reviewer added
- [x] Description added
- [ ] Unit test cases added

### Reviewer Checklist

- [ ] PR title starts with Jira ticket number prefix
- [ ] If hotfix, Add Hotfix as prefix in PR title
- [ ] Label added
- [ ] Commit messages follows standard format (added, changed, removed, code commented and chore)
- [ ] Description about the Feature/ Bugs added

2024-11-27 14:34 UTC, sidcr7-likeminds requested changes

2024-11-27 14:34 UTC, sidcr7-likeminds commented on feedsx/dependencies.gradle
> +    implementation 'community.likeminds:likemindsfeed:1.7.220'
update the version

2024-12-11 08:26 UTC, ishaan1607 commented on feedsx/dependencies.gradle
> +    implementation 'community.likeminds:likemindsfeed:1.7.220'
will revert the version post testing.

2024-12-11 14:11 UTC, sidcr7-likeminds approved these changes

2024-12-12 06:46 UTC, merged